スキーマ情報の追加
ih14c-13-14/schema pull request #2
Opened 2023-06-14 07:06 UTC by ryota658

# やったこと
- compornentの作成。
- auth, user, art関連のAPI設計

# やらないこと
- signoutとQR関連のAPI設計。QRの画面遷移の流れがわかり次第やる。

2023-06-15 00:40 UTC, ryota658 commented
こちらやまさんもレビューお願いします。

2023-06-15 02:05 UTC, na2na-p requested changes
変更範囲かなり広い、かつ多いので一旦ここまでで止めます。

差分デカすぎるので、方針として下記のような1リソース群ごとにPR出すとここまで辛くならないです（出したものは仕方ないので次からお願いします。

<img width="1470" alt="image" src="https://github.com/ih14c-13-14/schema/assets/49822810/4c624b30-8060-48ac-bf8a-7c72e9f2eda3">

2023-06-15 02:05 UTC, na2na-p commented on openapi/openapi.yml
> +        example: 12345
これだとnumberなので

```suggestion
        example: "12345"  
```

```suggestion
        example: "hello world"  
```

くらいにしておきましょうか

2023-06-15 02:05 UTC, na2na-p commented on openapi/openapi.yml
> +      in: path
他も含めて)本当に`in: path`するんですか？

2023-06-15 02:05 UTC, na2na-p commented on openapi/openapi.yml
> +      description: ユーザIDを渡し、保存した作品を返す。
```suggestion
      description: ユーザIDを渡し、お気に入りした作品を全件返す。
```

2023-06-19 04:09 UTC, ryota658 commented on openapi/openapi.yml
>     * バックエンドバリデーションはもうけるのか
  - 設けます
>     * バックエンドバリデーションに引っかかった場合に何返すか
  - 以下を返す。
```
{
  "statusCode": 400,
  "message": [
    {
      "property": "string",
      "message": "string"
    }
  ]
}
```

2023-06-19 04:18 UTC, ryota658 commented on openapi/openapi.yml
>        responses:
その認識で実装予定です。
JWTトークンの削除でもってログアウト。

2023-06-19 04:21 UTC, na2na-p commented on openapi/openapi.yml
>        responses:
削除の方法について
> JWT をログアウトに対応させる方法は [ブラックリスト](http://d.hatena.ne.jp/keyword/%A5%D6%A5%E9%A5%C3%A5%AF%A5%EA%A5%B9%A5%C8)を用意する か [トーク](http://d.hatena.ne.jp/keyword/%A5%C8%A1%BC%A5%AF)ンの有効期限を短くする の 2 つだけ

のようです。私の提案としては有効期限を短くする方です。どちらにしますか？

https://kawasin73.hatenablog.com/entry/2019/07/22/020650#:~:text=JWT%20%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%AD%E3%82%B0%E3%82%A2%E3%82%A6%E3%83%88&text=%E6%AE%8B%E5%BF%B5%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82,%E3%81%AE%202%20%E3%81%A4%E3%81%A0%E3%81%91%E3%81%A7%E3%81%99%E3%80%82

2023-06-19 04:44 UTC, Issiki0416 commented on openapi/openapi.yml
> +  /users/email-change/{user_id}:
/users/からで作成するとディレクトリの構造が下の画像みたいになるんかと思ってて、
 ` /{user_id}/email-change/ ` の場合ってどんなディレクトリになる？
<img width="187" alt="image" src="https://github.com/ih14c-13-14/schema/assets/96870513/6d501b35-899f-419c-8eaa-2dd2b21dcca0">

2023-06-19 04:52 UTC, na2na-p commented on openapi/openapi.yml
> +  /users/email-change/{user_id}:
前提の質問で

1. ルーティングはディレクトリベースを考えているのですか？

(そうではない、という前提で回答をすると)
ユーザという概念を扱うコントローラーである、ということには変わらないので、`/users/`から変えたところでこちらも揃える必要はないと思ってます。

また好奇心からの質問で)
resolverは何をするのですか？

2023-06-19 05:58 UTC, Issiki0416 commented on openapi/openapi.yml
> +  /users/email-change/{user_id}:
ああああ、ごめん
resolverは関係ない〜
コントローラーでやります

2023-06-19 07:20 UTC, ryota658 commented on openapi/openapi.yml
> +      responses:
> メールアドレスが重複した場合は？
- reponse code 409で返します。
```
{
  "statusCode": 409,
  "message": "メールアドレスは既に登録されています。"
}
```

2023-06-19 07:44 UTC, ryota658 commented on openapi/openapi.yml
> +  /auth/login:
- statusCode401で返します。
```
{
  "statusCode": 401,
  "message": "string"
}
```

2023-06-20 08:51 UTC, ryota658 commented on openapi/openapi.yml
> +  /arts/save/{user_id}:
> save

figmaが保存なのでそちらにあわせました。

![image](https://github.com/ih14c-13-14/schema/assets/80617274/8e86ac78-1287-44cb-ba91-ab6874b24d11)

2023-06-21 06:30 UTC, ryota658 commented on openapi/openapi.yml
> +          schema:
配列になります。修正しました。

2023-06-21 06:36 UTC, ryota658 commented on openapi/openapi.yml
追加しました。
>       2. バックエンドは、新しいメールアドレスに対し、トークンを付与した検証用リンクを送信する
>       4. フロントエンドは、URLに付与された検証用トークンをバックエンドに送信する
トークンを入れたリンクにさらにメールもリクエストパラメータとして付加して実装します。

2023-06-21 10:21 UTC, ryota658 commented on openapi/openapi.yml
> +    get:
単数取得用エンドポイントも追加しました。

2023-06-21 10:54 UTC, ryota658 commented on openapi/openapi.yml
>        responses:
> バックエンドバリデーション
> 
>     * 使用不可文字列書いた場合は？
使用不可文字列を入力された場合：RegExpで対応。
例： ?,.;:[]{}`+*_^
文字列の長さ制限を超えている場合：class-validatorでDTOに設定することで対応
https://yarnpkg.com/package/class-validator
例： @Max() 
文字列の長さ制限を違反した場合は、エラーメッセージを返す。
```
{
  "statusCode": 400,
  "message": [
    {
      "property": "string",
      "message": "string"
    }
  ]
}
```
>     * DB制約でユニーク制約書いてるのに抵触した場合は？
```
{
  "statusCode": 409,
  "message": string
}
```

2023-06-23 03:24 UTC, ryota658 commented on openapi/openapi.yml
>        responses:
> 削除の方法について
> 
> > JWT をログアウトに対応させる方法は [ブラックリスト](http://d.hatena.ne.jp/keyword/%A5%D6%A5%E9%A5%C3%A5%AF%A5%EA%A5%B9%A5%C8)を用意する か [トーク](http://d.hatena.ne.jp/keyword/%A5%C8%A1%BC%A5%AF)ンの有効期限を短くする の 2 つだけ
>
> のようです。私の提案としては有効期限を短くする方です。どちらにしますか？
有効期限を短くする方で実装します。

2023-06-23 04:27 UTC, Issiki0416 approved these changes

2023-06-23 04:27 UTC, Issiki0416 commented on openapi/openapi.yml
> +  /users/email-change/{user_id}:
> (任意・提案)
> 
> というのはどうでしょうか。他のusersから始まるものの全て共通

結論：開発ではnest cli でコントローラーを作成するので、` /users/email-change/{user_id} `にしたい。 


前提として、`/{user_id}/email-change/` が可能かどうか実験してみたところ可能でした。（GETでやりました）

### controller側
` @Controller('') ` でわかるように、せっかくnest cliでコントローラーを作成した際の
ルーティングを消す形になった。
``` 
import { Controller, Get, Param } from '@nestjs/common';
import { UserService } from './user.service';

@Controller('')
export class UserController {
  constructor(private readonly userService: UserService) {}

  @Get(':user_id/email-change')
  findAll(@Param('user_id') userId: string) {
    return this.userService.findAll(userId);
  }
}
```

### パラメーターにuserIdをもたせる
<img width="498" alt="image" src="https://github.com/ih14c-13-14/schema/assets/96870513/4b37a3ae-0351-47d4-82aa-e1664636daa9">

### sendするとレスポンスとしてuserIdの取得を確認
<img width="505" alt="image" src="https://github.com/ih14c-13-14/schema/assets/96870513/5ce60b2d-3c94-4441-bf8f-f1088948626d">


### ルーティングされてることの確認
<img width="680" alt="image" src="https://github.com/ih14c-13-14/schema/assets/96870513/9564e8e9-2ebd-4fc2-8dba-0807dc47f910">
  
## まとめ
開発ではnest cliでコントローラーを作成します。(`nest g controller users ` )
作成後のコントローラーのルーティングが` @Controller('users') ` に設定されるのでこれを変えたくないのが
バックエンドの意見です。

2023-06-23 04:40 UTC, na2na-p commented on openapi/openapi.yml
> +  /users/email-change/{user_id}:
フレームワークに乗っかりたい、理解しました。このままで大丈夫です

2023-06-27 09:16 UTC, Issiki0416 commented
確認しました。

2023-06-27 09:18 UTC, Issiki0416 approved these changes
確認しました

2023-06-27 10:01 UTC, na2na-p approved these changes

2023-06-27 10:02 UTC, merged